### ISSUE TITLE
Definiting path parameters in the PathItem instead of Operation

### ISSUE THREAD

**Issue by commonism** [DMTF/Redfish-Tools#466]
I propose to define path parameters in the PathItem definition instead of the Operation to reduce the number of definitions/lines in the description document

Instead of:

```yaml
  /redfish/v1/TaskService/Tasks/{TaskId}:
    delete:
      parameters:
      - description: The value of the Id property of the Task resource
        in: path
        name: TaskId
        required: true
        schema:
          type: string
…
    get:
      parameters:
      - description: The value of the Id property of the Task resource
        in: path
        name: TaskId
        required: true
        schema:
          type: string
…
```

```yaml
  /redfish/v1/TaskService/Tasks/{TaskId}:
    parameters:
      - description: The value of the Id property of the Task resource
        in: path
        name: TaskId
        required: true
        schema:
          type: string

    delete:
…
    get:
…
``
