### ISSUE TITLE
possibly Invalid pattern for Passphrase

### ISSUE THREAD

**Issue by commonism** [DMTF/Redfish-Tools#480]
The regex

```yaml
          pattern: (^[ !#-~]+$)|(^Passphrase:[ ^[ !#-~]+$)|(^Hex:[0-9A-Fa-f]{24})|(^\*+$)
          pattern: (^[ !#-~]+$)|(^Passphrase:[ ^[ !#-~]+$)|(^Hex:[0-9A-Fa-f]{24,96})|(^\*+$)
          pattern: (^[ !#-~]+$)|(^Passphrase:[ ^[ !#-~]+$)|(^Hex:[0-9A-Fa-f]{32})|(^\*+$)
```

are considered invalid by rust regex. 
```
  SchemaError: regex parse error:
    (^[ !#-~]+$)|(^Passphrase:[ ^[ !#-~]+$)|(^Hex:[0-9A-Fa-f]{24,96})|(^\*+$)
                              ^
error: unclosed character class
```
It's accepted by python re.

Yet I think it lacks an escape for the `[` in `^[`
```
(^Passphrase:[ ^\[ !#-~]+$)
```
